# Netlist Viewer TCL File
set_family -name SmartFusion2
top_module -name Mario_Libero
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/Mario_Libero/CoreGPIO_0/rtl/vlog/core/coregpio.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/Mario_Libero/FCCC_0/Mario_Libero_FCCC_0_FCCC.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/Actel/SgCore/OSC/2.0.101/osc_comps.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/Mario_Libero/OSC_0/Mario_Libero_OSC_0_OSC.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/cm_if_apb.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/fifo_error_decoder.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/ack_datapath.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/nmic_rx.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/nmic_tx.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/twoMHz_strobe.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/corefifo_doubleSync.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/ADCFIFO_ADCFIFO_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/ADCFIFO_ADCFIFO_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/ADCFIFO/ADCFIFO.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/ADCMEM_DP.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/adc_frame_buffer.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/adc_vector_compressor.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/associative_memory.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/cellular_automaton.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/spatial_accumulator.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/spatial_encoder_ping_pong.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/hypervector_manipulator.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/similarity_bundler.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/temporal_encoder.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/fifo.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/feature_encoder.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\Users\bwrc\Desktop\HyperFlexEG\hdl}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/hdc_top.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/adc_datapath/adc_datapath.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/nm_channel/nm_channel.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/nm_if_apb.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/corefifo_doubleSync.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/PDMAFIFO_PDMAFIFO_0_USRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/PDMAFIFO_PDMAFIFO_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/PDMAFIFO/PDMAFIFO.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/hdl/pdma_if.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/nm_if/nm_if.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/cm_top/cm_top.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core_obfuscated/coreapb3_muxptob3.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core_obfuscated/coreapb3_iaddr_reg.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core_obfuscated/coreapb3.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/Mario_Libero_MSS/Mario_Libero_MSS_syn.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/Mario_Libero_MSS/Mario_Libero_MSS.v}
addfile -view RTL -lib work -type VLOG -mode verilog_2k -name {C:/Users/bwrc/Desktop/HyperFlexEG/component/work/Mario_Libero/Mario_Libero.v}
addfile -view HIER -lib work -type EDIF -mode NONE -name {C:/Users/bwrc/Desktop/HyperFlexEG/synthesis/Mario_Libero.edn}